export const products = [
  // Platillos (3 items)
  {
    id: 'PLA1',
    name: 'Sopa de Pollo',
    uom: 'kg',
    cost: 5,
    qty: 10,
    active: true,
    price: 15,
    type: 'Platillo',
    warehouseID: 'INV3',
    description: 'Deliciosa sopa de pollo casera',
    expireDate: '16/12/2024',
    providerId: 'P2',
  },
  {
    id: 'PLA2',
    name: 'Pasta con Albóndigas',
    uom: 'kg',
    cost: 8,
    qty: 8,
    active: true,
    price: 18,
    type: 'Platillo',
    warehouseID: 'INV3',
    description: 'Platillo de pasta con albóndigas en salsa de tomate',
    expireDate: '16/12/2024',
    providerId: 'P1',
  },
  {
    id: 'PLA3',
    name: 'Arroz Chino',
    uom: 'kg',
    cost: 6,
    qty: 12,
    active: true,
    price: 20,
    type: 'Platillo',
    warehouseID: 'INV3',
    description: 'Clásico arroz chino con verduras y pollo',
    expireDate: '16/12/2024',
    providerId: 'P3',
  },
  // Insumos (6 items)
  {
    id: 'INS1',
    name: 'Olla Renaware con tapa de 7,5 litros',
    uom: 'lt',
    cost: 40,
    qty: 5,
    active: true,
    price: 60,
    type: 'Insumo',
    warehouseID: 'INV2',
    description: 'Insumo para hervir pasta, cocer al vapor verduras y cocinar sopas y guisos',
    expireDate: '16/12/2080',
    providerId: 'P1',
  },
  {
    id: 'INS2',
    name: 'Sartén antiadherente Renaware de 30,5cm',
    uom: 'lt',
    cost: 30,
    qty: 7,
    active: true,
    price: 45,
    type: 'Insumo',
    warehouseID: 'INV2',
    description: 'Insumo para cocinar carnes y verduras salteadas',
    expireDate: '16/12/2075',
    providerId: 'P2',
  },
  {
    id: 'INS3',
    name: 'Cuchillo de Chef 8 pulgadas',
    uom: 'pcs',
    cost: 15,
    qty: 10,
    active: true,
    price: 25,
    type: 'Insumo',
    warehouseID: 'INV2',
    description: 'Insumo para cortar y picar alimentos con precisión',
    expireDate: '16/12/2090',
    providerId: 'P3',
  },
  {
    id: 'INS4',
    name: 'Manteles de Mesa (paquete de 10)',
    uom: 'pcs',
    cost: 12,
    qty: 20,
    active: true,
    price: 20,
    type: 'Insumo',
    warehouseID: 'INV2',
    description: 'Insumo para cubrir y decorar mesas en eventos',
    expireDate: '16/12/2025',
    providerId: 'P1',
  },
  {
    id: 'INS5',
    name: 'Guantes de Cocina (par)',
    uom: 'pcs',
    cost: 5,
    qty: 30,
    active: true,
    price: 8,
    type: 'Insumo',
    warehouseID: 'INV2',
    description: 'Insumo para proteger las manos al cocinar',
    expireDate: '16/12/2026',
    providerId: 'P2',
  },
  {
    id: 'INS6',
    name: 'Paño de Limpieza (pack de 5)',
    uom: 'pcs',
    cost: 4,
    qty: 25,
    active: true,
    price: 7,
    type: 'Insumo',
    warehouseID: 'INV2',
    description: 'Insumo para limpiar superficies y utensilios de cocina',
    expireDate: '16/12/2026',
    providerId: 'P3',
  },
  // Ingredientes (8 items)
  {
    id: 'ING1',
    name: 'Mantequilla',
    uom: 'kg',
    cost: 3,
    qty: 15,
    active: true,
    price: 5,
    type: 'Ingrediente',
    warehouseID: 'INV1',
    description: 'Ingrediente para untar y cocinar',
    expireDate: '16/12/2023',
    providerId: 'P1',
  },
  {
    id: 'ING2',
    name: 'Aceite de Oliva',
    uom: 'lt',
    cost: 10,
    qty: 8,
    active: true,
    price: 15,
    type: 'Ingrediente',
    warehouseID: 'INV1',
    description: 'Ingrediente esencial para cocinar',
    expireDate: '16/12/2023',
    providerId: 'P2',
  },
  {
    id: 'ING3',
    name: 'Harina de Trigo',
    uom: 'kg',
    cost: 2,
    qty: 20,
    active: true,
    price: 4,
    type: 'Ingrediente',
    warehouseID: 'INV1',
    description: 'Ingrediente básico para repostería y panadería',
    expireDate: '16/12/2024',
    providerId: 'P3',
  },
  {
    id: 'ING4',
    name: 'Pasta de Espagueti',
    uom: 'kg',
    cost: 1.5,
    qty: 30,
    active: true,
    price: 3,
    type: 'Ingrediente',
    warehouseID: 'INV1',
    description: 'Ingrediente para preparar deliciosos platillos de pasta',
    expireDate: '16/12/2024',
    providerId: 'P1',
  },
  {
    id: 'ING5',
    name: 'Carne de Res',
    uom: 'kg',
    cost: 8,
    qty: 10,
    active: true,
    price: 12,
    type: 'Ingrediente',
    warehouseID: 'INV1',
    description: 'Ingrediente principal para carnes asadas y guisos',
    expireDate: '16/12/2024',
    providerId: 'P2',
  },
  {
    id: 'ING6',
    name: 'Pescado Fresco',
    uom: 'kg',
    cost: 12,
    qty: 6,
    active: true,
    price: 18,
    type: 'Ingrediente',
    warehouseID: 'INV1',
    description: 'Ingrediente para preparar deliciosos platillos de pescado',
    expireDate: '16/12/2024',
    providerId: 'P3',
  },
  {
    id: 'ING7',
    name: 'Cebollas',
    uom: 'kg',
    cost: 2,
    qty: 25,
    active: true,
    price: 4,
    type: 'Ingrediente',
    warehouseID: 'INV1',
    description: 'Ingrediente esencial para sazonar y dar sabor a los platillos',
    expireDate: '16/12/2023',
    providerId: 'P1',
  },
  {
    id: 'ING8',
    name: 'Lechuga Fresca',
    uom: 'kg',
    cost: 2.5,
    qty: 18,
    active: true,
    price: 5,
    type: 'Ingrediente',
    warehouseID: 'INV1',
    description: 'Ingrediente para ensaladas y hamburguesas',
    expireDate: '16/12/2023',
    providerId: 'P2',
  },
];
